# Generated by Django 5.1.7 on 2025-04-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moma', '0002_remove_customuser_password_hash_project_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='deadline',
            new_name='due_date',
        ),
    ]
