# Generated by Django 5.1.7 on 2025-04-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moma', '0003_rename_deadline_project_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('awaiting_approval', 'Awaiting Approval'), ('editing', 'Editing'), ('done', 'Done')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('awaiting_approval', 'Awaiting Approval'), ('editing', 'Editing'), ('done', 'Done')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('awaiting_approval', 'Awaiting Approval'), ('editing', 'Editing'), ('done', 'Done')], default='not_started', max_length=20),
        ),
    ]
