# Generated by Django 5.1.7 on 2025-04-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moma', '0004_alter_project_status_alter_subtask_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('awaiting_approval', 'Awaiting Approval'), ('editing', 'Editing'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('awaiting_approval', 'Awaiting Approval'), ('editing', 'Editing'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('awaiting_approval', 'Awaiting Approval'), ('editing', 'Editing'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='not_started', max_length=20),
        ),
    ]
