# Generated by Django 5.1.7 on 2025-04-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moma', '0006_alter_client_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospective', 'Prospective'), ('removed', 'Removed')], default='active', max_length=20),
        ),
    ]
