# Generated by Django 5.1.7 on 2025-04-18 18:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moma', '0007_alter_client_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookkeeping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=255)),
                ('business', models.CharField(max_length=255)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document', models.FileField(upload_to='bookkeeping/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'docx'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
