# Generated by Django 5.1.7 on 2025-04-19 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moma', '0008_bookkeeping_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeeping',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookkeeping',
            name='business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookkeeping',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='bookkeeping/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='bookkeeping',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookkeeping',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
