# Generated by Django 5.1.7 on 2025-04-19 12:44

import django.core.validators
import moma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moma', '0009_alter_bookkeeping_amount_alter_bookkeeping_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeeping',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='bookkeeping',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=moma.models.Bookkeeping.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'docx']), moma.models.validate_file_size]),
        ),
    ]
