# Generated by Django 5.1.7 on 2025-04-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moma', '0010_alter_bookkeeping_amount_alter_bookkeeping_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='moma.client'),
        ),
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='moma.client'),
        ),
    ]
