# Generated by Django 5.1.7 on 2025-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moma', '0011_alter_project_client_alter_task_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_my_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_my_business',
            field=models.BooleanField(default=False),
        ),
    ]
