# Generated by Django 4.2.20 on 2025-04-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moma', '0013_bookkeeping_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeeping',
            name='converted_pdf',
            field=models.FileField(blank=True, null=True, upload_to='converted_pdfs/'),
        ),
    ]
